apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix
  labels:
    app.kubernetes.io/name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: DB_SERVER_PORT
              value: "5432"
            - name: DB_SERVER_DBNAME
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: POSTGRES_PASSWORD
            - name: ZBX_SERVER_HOST
              value: zabbix-server
            - name: ZBX_SERVER_PORT
              value: "10051"
            - name: PHP_TZ
              value: Asia/Bishkek
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: zabbix
  labels:
    app.kubernetes.io/name: zabbix-web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: zabbix-web
