apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: zabbix-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-postgres
  serviceName: zabbix-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image.postgres | quote }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: zabbix-db-secret
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.resources.postgres.requests.cpu | quote }}
              memory: {{ .Values.resources.postgres.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.postgres.limits.cpu | quote }}
              memory: {{ .Values.resources.postgres.limits.memory | quote }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.storage | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: zabbix-postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: zabbix-postgres
