name: zabbix-k8s-ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-deploy:
    name: Kind deploy & smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: zbx

      - name: Show tool versions
        run: |
          kubectl version --client
          helm version

      # ---------- Deploy ----------
      - name: Apply manifests
        run: |
          kubectl apply -f manifests/00-namespace.yaml
          kubectl apply -f manifests/10-secret-db.yaml
          kubectl apply -f manifests/20-postgres-sts.yaml
          kubectl apply -f manifests/30-zabbix-server-deploy.yaml
          kubectl apply -f manifests/40-zabbix-web-deploy.yaml
          kubectl apply -f manifests/50-ingress.yaml

      - name: Wait for readiness
        run: |
          kubectl -n zabbix wait --for=condition=available deploy/zabbix-server --timeout=600s
          kubectl -n zabbix wait --for=condition=available deploy/zabbix-web --timeout=600s
          kubectl -n zabbix get pods -o wide

      # ---------- Smoke test (HTTP 200 and "Zabbix" in HTML) ----------
      - name: HTTP check from inside cluster
        run: |
          kubectl -n zabbix run curl --image=curlimages/curl:8.9.1 --restart=Never --rm -i -- \
            sh -c 'curl -s -o - http://zabbix-web.zabbix.svc.cluster.local/ | tee /dev/stderr | grep -qi "Zabbix"'

      # ---------- Package artifacts ----------
      - name: Create tar.gz bundle
        run: |
          tar -czf zabbix-k8s-bundle.tar.gz manifests helm

      - name: Upload test artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: zabbix-k8s-bundle
          path: zabbix-k8s-bundle.tar.gz

  publish:
    name: Publish to Docker Hub (OCI chart + image with bundle)
    if: github.event_name != 'pull_request'
    needs: [test-deploy]
    runs-on: ubuntu-latest
    env:
      REGISTRY_OCI: registry-1.docker.io             # для Helm OCI пуша
      REGISTRY_DOCKER: docker.io                      # для docker image пуша
      REPO_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read chart version
        id: chartver
        run: |
          VER=$(grep '^version:' helm/zabbix-mini-chart/Chart.yaml | awk '{print $2}')
          echo "ver=${VER}" >> $GITHUB_OUTPUT

      - name: Package Helm chart
        run: |
          helm package helm/zabbix-mini-chart
          ls -l *.tgz

      - name: Login to Docker Hub (OCI for Helm)
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login $REGISTRY_OCI \
            --username "${{ env.REPO_NAMESPACE }}" --password-stdin

      - name: Push Helm chart to Docker Hub (OCI)
        run: |
          HELM_TGZ="zabbix-mini-chart-${{ steps.chartver.outputs.ver }}.tgz"
          helm push "$HELM_TGZ" oci://$REGISTRY_OCI/${{ env.REPO_NAMESPACE }}

      # ---------- Image with tar.gz bundle ----------
      - name: Create tar.gz bundle (again for image context)
        run: |
          tar -czf zabbix-k8s-bundle.tar.gz manifests helm

      - name: Login to Docker Hub (classic)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_DOCKER }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image carrying tar.gz
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/Dockerfile.bundle
          push: true
          tags: ${{ env.REGISTRY_DOCKER }}/${{ env.REPO_NAMESPACE }}/zabbix-k8s-bundle:manifests-${{ steps.chartver.outputs.ver }}
